import pathlib

HERE = pathlib.Path(__file__).parent
IK_CONFIG_ROOT = HERE / "ik_configs"
ASSET_ROOT = HERE / ".." / "assets"

ROBOT_XML_DICT = {
    "agibot_a2": ASSET_ROOT / "agibot_a2" / "mujoco" / "model.xml",
    "berkeley_humanoid_lite": ASSET_ROOT / "berkeley_humanoid_lite" / "berkeley_humanoid_lite.xml",
    "booster_k1": ASSET_ROOT / "booster_k1" / "K1_serial.xml",
    "booster_t1": ASSET_ROOT / "booster_t1" / "T1_serial.xml",
    "booster_t1_29dof": ASSET_ROOT / "booster_t1_29dof" / "t1_mocap.xml",
    "engineai_pm01": ASSET_ROOT / "engineai_pm01" / "xml" / "serial_pm_v2.xml",
    "fourier_gr3": ASSET_ROOT / "fourier_gr3v2_1_1" / "mjcf" / "gr3v2_1_1_dummy_hand.xml",
    "fourier_n1": ASSET_ROOT / "fourier_n1" / "n1_mocap.xml",
    "galaxea_r1pro": ASSET_ROOT / "galaxea_r1pro" / "r1_pro.xml",
    "hightorque_hi": ASSET_ROOT / "hightorque_hi" / "hi_25dof.xml",
    "kuavo_s45": ASSET_ROOT / "kuavo_s45" / "biped_s45_collision.xml",
    "openloong": ASSET_ROOT / "openloong" / "AzureLoong.xml",
    "pal_talos": ASSET_ROOT / "pal_talos" / "talos.xml",
    "pnd_adam_lite": ASSET_ROOT / "pnd_adam_lite" / "adam_lite.xml",
    "stanford_toddy": ASSET_ROOT / "stanford_toddy" / "toddy_mocap.xml",
    "tienkung": ASSET_ROOT / "tienkung" / "mjcf" / "tienkung.xml",
    "unitree_g1_23dof": ASSET_ROOT / "unitree_g1" / "g1_23dof_rev_1_0.xml",
    "unitree_g1_29dof": ASSET_ROOT / "unitree_g1" / "g1_mocap_29dof.xml",
    "unitree_g1_with_hands": ASSET_ROOT / "unitree_g1" / "g1_mocap_29dof_with_hands.xml",
    "unitree_h1": ASSET_ROOT / "unitree_h1" / "h1.xml",
    "unitree_h1_2": ASSET_ROOT / "unitree_h1_2" / "h1_2_handless.xml",
}

IK_CONFIG_DICT = {
    # offline data
    "smplx": {
        # "agibot_a2": IK_CONFIG_ROOT / "smplx_to_a2.json",
        "berkeley_humanoid_lite": IK_CONFIG_ROOT / "smplx_to_bhl.json",
        "booster_k1": IK_CONFIG_ROOT / "smplx_to_k1.json",
        "booster_t1": IK_CONFIG_ROOT / "smplx_to_t1.json",
        "booster_t1_29dof": IK_CONFIG_ROOT / "smplx_to_t1_29dof.json",
        "engineai_pm01": IK_CONFIG_ROOT / "smplx_to_pm01.json",
        "fourier_gr3": IK_CONFIG_ROOT / "smplx_to_gr3.json",
        "fourier_n1": IK_CONFIG_ROOT / "smplx_to_n1.json",
        # "galaxea_r1pro": IK_CONFIG_ROOT / "smplx_to_r1pro.json",
        "hightorque_hi": IK_CONFIG_ROOT / "smplx_to_hi.json",
        "kuavo_s45": IK_CONFIG_ROOT / "smplx_to_kuavo.json",
        # "openloong": IK_CONFIG_ROOT / "smplx_to_openloong.json",
        "pal_talos": IK_CONFIG_ROOT / "smplx_to_talos.json",
        "pnd_adam_lite": IK_CONFIG_ROOT / "smplx_to_adam.json",
        "stanford_toddy": IK_CONFIG_ROOT / "smplx_to_toddy.json",
        "tienkung": IK_CONFIG_ROOT / "smplx_to_tienkung.json",
        "unitree_g1_23dof": IK_CONFIG_ROOT / "smplx_to_g1_23dof.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "smplx_to_g1.json",
        # "unitree_g1_with_hands": IK_CONFIG_ROOT / "smplx_to_g1.json",
        "unitree_h1": IK_CONFIG_ROOT / "smplx_to_h1.json",
        "unitree_h1_2": IK_CONFIG_ROOT / "smplx_to_h1_2.json",
    },
    "bvh_lafan1": {
        # "agibot_a2": IK_CONFIG_ROOT / "bvh_lafan1_to_a2.json",
        "berkeley_humanoid_lite": IK_CONFIG_ROOT / "bvh_lafan1_to_bhl.json",
        "booster_k1": IK_CONFIG_ROOT / "bvh_lafan1_to_k1.json",
        "booster_t1": IK_CONFIG_ROOT / "bvh_lafan1_to_t1.json",
        "booster_t1_29dof": IK_CONFIG_ROOT / "bvh_lafan1_to_t1_29dof.json",
        "engineai_pm01": IK_CONFIG_ROOT / "bvh_lafan1_to_pm01.json",
        "fourier_gr3": IK_CONFIG_ROOT / "bvh_lafan1_to_gr3.json",
        "fourier_n1": IK_CONFIG_ROOT / "bvh_lafan1_to_n1.json",
        "hightorque_hi": IK_CONFIG_ROOT / "bvh_lafan1_to_hi.json",
        "kuavo_s45": IK_CONFIG_ROOT / "bvh_lafan1_to_kuavo.json",
        # "openloong": IK_CONFIG_ROOT / "bvh_lafan1_to_openloong.json",
        "pal_talos": IK_CONFIG_ROOT / "bvh_lafan1_to_talos.json",
        "pnd_adam_lite": IK_CONFIG_ROOT / "bvh_lafan1_to_adam.json",
        "stanford_toddy": IK_CONFIG_ROOT / "bvh_lafan1_to_toddy.json",
        "tienkung": IK_CONFIG_ROOT / "bvh_lafan1_to_tienkung.json",
        "unitree_g1_23dof": IK_CONFIG_ROOT / "bvh_lafan1_to_g1_23dof.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "bvh_lafan1_to_g1.json",
        # "unitree_g1_with_hands": IK_CONFIG_ROOT / "bvh_lafan1_to_g1.json",
        "unitree_h1": IK_CONFIG_ROOT / "bvh_lafan1_to_h1.json",
        "unitree_h1_2": IK_CONFIG_ROOT / "bvh_lafan1_to_h1_2.json",
    },
    "bvh_nokov": {
        "unitree_g1": IK_CONFIG_ROOT / "bvh_nokov_to_g1.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "bvh_nokov_to_g1.json",
    },
    "bvh_xsens": {
        "unitree_g1": IK_CONFIG_ROOT / "bvh_xsens_to_g1.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "bvh_xsens_to_g1.json",
        "unitree_h1_2": IK_CONFIG_ROOT / "bvh_xsens_to_h1_2.json",
    },
    "fbx": {
        "unitree_g1": IK_CONFIG_ROOT / "fbx_to_g1.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "fbx_to_g1.json",
        "unitree_g1_with_hands": IK_CONFIG_ROOT / "fbx_to_g1.json",
    },
    "fbx_offline": {
        "unitree_g1": IK_CONFIG_ROOT / "fbx_offline_to_g1.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "fbx_offline_to_g1.json",
    },
    
    "xrobot": {
        "unitree_g1": IK_CONFIG_ROOT / "xrobot_to_g1.json",
        "unitree_g1_29dof": IK_CONFIG_ROOT / "xrobot_to_g1.json",
    },
    "xsens_mvn": {
        "unitree_g1": IK_CONFIG_ROOT / "xsens_mvn_to_g1.json",
    },
}


ROBOT_BASE_DICT = {
    "agibot_a2": "torso",
    "berkeley_humanoid_lite": "imu_2",
    "booster_k1": "Trunk",
    "booster_t1": "Waist",
    "booster_t1_29dof": "Waist",
    "engineai_pm01": "LINK_BASE",
    "fourier_gr3": "base_link",
    "fourier_n1": "base_link",
    "galaxea_r1pro": "torso_link4",
    "hightorque_hi": "base_link",
    "kuavo_s45": "base_link",
    "openloong": "base_link",
    "pal_talos": "base_link",
    "pnd_adam_lite": "pelvis",
    "stanford_toddy": "waist_link",
    "tienkung": "Base_link",
    "unitree_g1": "pelvis",
    "unitree_g1_23dof": "pelvis",
    "unitree_g1_29dof": "pelvis",
    "unitree_g1_with_hands": "pelvis",
    "unitree_h1": "pelvis",
    "unitree_h1_2": "pelvis",
}

VIEWER_CAM_DISTANCE_DICT = {
    "agibot_a2": 2.0,
    "berkeley_humanoid_lite": 2.0,
    "booster_k1": 2.0,
    "booster_t1": 2.0,
    "booster_t1_29dof": 2.0,
    "engineai_pm01": 2.0,
    "fourier_gr3": 2.0,
    "fourier_n1": 2.0,
    "galaxea_r1pro": 3.0,
    "hightorque_hi": 2.0,
    "kuavo_s45": 3.0,
    "openloong": 3.0,
    "pal_talos": 3.0,
    "pnd_adam_lite": 3.0,
    "stanford_toddy": 1.0,
    "tienkung": 3.0,
    "unitree_g1": 2.0,
    "unitree_g1_23dof": 2.0,
    "unitree_g1_29dof": 2.0,
    "unitree_g1_with_hands": 2.0,
    "unitree_h1": 3.0,
    "unitree_h1_2": 3.0,
}
